In [1]:
import numpy as np
import pandas as pd

In [7]:
import plotly.express as px
import pandas as pd

df = pd.read_csv("homework/result_1.csv")
fig = px.parallel_coordinates(df,
                             color_continuous_midpoint=3, height=512, width=1024)
fig.show()
fig.write_image("result_1.svg", )

In [8]:
df.columns

Index(['iterations_N', 'quantile_params', 'trajectories_K', 'max_iter',
       'best_mean_total_reward'],
      dtype='object')

In [8]:
m = np.random.randint(1, 100, (5,5))
m

array([[83, 89, 58,  8, 95],
       [63, 72, 56, 74, 65],
       [78, 90, 35, 59, 29],
       [ 7, 49,  4, 38, 79],
       [94, 10,  6, 30, 40]])

In [15]:
m[np.array(m > 10)]

array([83, 89, 58, 95, 63, 72, 56, 74, 65, 78, 90, 35, 59, 29, 49, 38, 79,
       94, 30, 40])

In [19]:
t = np.where(m > 10, m, 0)
t

array([[83, 89, 58,  0, 95],
       [63, 72, 56, 74, 65],
       [78, 90, 35, 59, 29],
       [ 0, 49,  0, 38, 79],
       [94,  0,  0, 30, 40]])

In [21]:
np.where(t == 0, t, t + 200)

array([[283, 289, 258,   0, 295],
       [263, 272, 256, 274, 265],
       [278, 290, 235, 259, 229],
       [  0, 249,   0, 238, 279],
       [294,   0,   0, 230, 240]])

In [23]:
assert True

In [29]:
policy_lambda = 0.1
assert 0 < policy_lambda <= 1

In [50]:
a = np.zeros((4,4)) + 0.25

In [51]:
np.random.Generator.choice(np.random.randn(5,5), p=np.random.randn(5,5))

TypeError: descriptor 'choice' for 'numpy.random._generator.Generator' objects doesn't apply to a 'numpy.ndarray' object

In [52]:
np.random.choice(a[0], p=a[0])

0.25

In [53]:
a[0,:]

array([0.25, 0.25, 0.25, 0.25])

In [49]:
a

array([[0.25, 0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25, 0.25]])